name: The Imperial Formation
favicon: null
layout_spectrum: 0.36601
typography_spectrum: 0.95064
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#454545'
    - '#959595'
    - '#676767'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
