name: The Imperial Formation
favicon: null
layout_spectrum: 0.7404846223071218
typography_spectrum: 0.012402838561683893
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6114388380665332
  lightness: 0.7540455579292029
  saturation: 0.8087989594787359
  rhythmicContrast: 0.2685497594065964
purpose: []
